version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=NetEase App
    volumes:
      - .:/app
    command: uvicorn src.cat.api.main:app --host 0.0.0.0 --port 8000 --reload
